2016-07-20 18:47:26,661 ERROR HIH-D-5272-0 thread-1 [ run-0 ]: aborted run - Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	success = self.syncCli.createRCWaitRunning(rcName, namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 24, in createRC
	self.testWrapper1(resourcename, self.namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 67, in __call__
java.lang.NoClassDefFoundError: Could not initialize class com.netease.qa.nce.util.Template
	at com.netease.qa.nce.test.BasicAPIClient.createResource(BasicAPIClient.java:139) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.test.SyncAPIClient.createRCWaitRunning(SyncAPIClient.java:53) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.createRC$3(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:26) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:166) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:338) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$7(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:73) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
2016-07-20 18:47:26,669 ERROR HIH-D-5272-0 thread-3 [ run-0 ]: aborted run - Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	success = self.syncCli.createRCWaitRunning(rcName, namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 24, in createRC
	self.testWrapper1(resourcename, self.namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 67, in __call__
java.lang.NoClassDefFoundError: Could not initialize class com.netease.qa.nce.util.Template
	at com.netease.qa.nce.test.BasicAPIClient.createResource(BasicAPIClient.java:139) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.test.SyncAPIClient.createRCWaitRunning(SyncAPIClient.java:53) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.createRC$3(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:26) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:166) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:338) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$7(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:73) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
2016-07-20 18:47:26,671 ERROR HIH-D-5272-0 thread-0 [ run-0 ]: aborted run - Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	success = self.syncCli.createRCWaitRunning(rcName, namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 24, in createRC
	self.testWrapper1(resourcename, self.namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 67, in __call__
java.lang.NoClassDefFoundError: Could not initialize class com.netease.qa.nce.util.Template
	at com.netease.qa.nce.test.BasicAPIClient.createResource(BasicAPIClient.java:139) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.test.SyncAPIClient.createRCWaitRunning(SyncAPIClient.java:53) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.createRC$3(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:26) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:166) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:338) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$7(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:73) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
2016-07-20 18:47:26,671 ERROR HIH-D-5272-0 thread-2 [ run-0 ]: aborted run - Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	success = self.syncCli.createRCWaitRunning(rcName, namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 24, in createRC
	self.testWrapper1(resourcename, self.namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 67, in __call__
java.lang.ExceptionInInitializerError: null
	at com.netease.qa.nce.test.BasicAPIClient.createResource(BasicAPIClient.java:139) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.test.SyncAPIClient.createRCWaitRunning(SyncAPIClient.java:53) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.createRC$3(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:26) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:166) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:338) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$7(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:73) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
Caused by: net.sf.json.JSONException: A JSONArray text must start with '[' at character 0 of 
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:505) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at net.sf.json.JSONArray._fromJSONTokener(JSONArray.java:1117) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at net.sf.json.JSONArray._fromString(JSONArray.java:1198) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at net.sf.json.JSONArray.fromObject(JSONArray.java:127) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at net.sf.json.JSONArray.fromObject(JSONArray.java:105) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.util.Template.<clinit>(Template.java:69) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	... 33 common frames omitted
2016-07-20 18:47:26,671 ERROR HIH-D-5272-0 thread-4 [ run-0 ]: aborted run - Java exception calling TestRunner
net.grinder.scriptengine.jython.JythonScriptExecutionException: Java exception calling TestRunner
	success = self.syncCli.createRCWaitRunning(rcName, namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 24, in createRC
	self.testWrapper1(resourcename, self.namespace)
	File "E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py", line 67, in __call__
java.lang.NoClassDefFoundError: Could not initialize class com.netease.qa.nce.util.Template
	at com.netease.qa.nce.test.BasicAPIClient.createResource(BasicAPIClient.java:139) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at com.netease.qa.nce.test.SyncAPIClient.createRCWaitRunning(SyncAPIClient.java:53) ~[perftest-0.1.4.3-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186) ~[jython.jar:na]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:422) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:426) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.createRC$3(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:26) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:166) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:338) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:139) ~[jython.jar:na]
	at org.python.pycode._pyx1.__call__$7(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py:73) ~[na:na]
	at org.python.pycode._pyx1.call_function(E:\eclipse_workdir\K8S_API_TEST\k8s_api_java.py) ~[na:na]
	at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[jython.jar:na]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194) ~[jython.jar:na]
	at org.python.core.PyFunction.__call__(PyFunction.java:387) ~[jython.jar:na]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:211) ~[jython.jar:na]
	at org.python.core.PyMethod.__call__(PyMethod.java:206) ~[jython.jar:na]
	at org.python.core.PyObject.invoke(PyObject.java:3555) ~[jython.jar:na]
	at org.python.core.PyInstance.instance___call__(PyInstance.java:351) ~[jython.jar:na]
	at org.python.core.PyInstance.__call__(PyInstance.java:342) ~[jython.jar:na]
	at org.python.core.PyObject.__call__(PyObject.java:371) ~[jython.jar:na]
	at net.grinder.scriptengine.jython.JythonScriptEngine$JythonWorkerRunnable.run(JythonScriptEngine.java:263) ~[grinder-core-3.11.jar:na]
	at net.grinder.engine.process.GrinderThread.run(GrinderThread.java:119) ~[grinder-core-3.11.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
